name: 'Dependency Review'
on: [pull_request, merge_group]

permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15

      - name: Dependency Review
        uses: actions/dependency-review-action@bc41886e18ea39df68b1b1245f4184881938e050 # v4.7.2
        with:
          config-file: './.github/dependency_review.yml'
          base-ref: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_ref }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
